{
    'name': 'نظام إدارة المخازن',
    'version': '1.0',
    'summary': 'anything',
    'auther': 'ITI',
    'description': "ay7aga",
    'website': 'http://www.iti.gov.eg',
    'depends': ['base'],
    'data': ['ERP_Project_view.xml',
 	'ERPProject_view.xml','security/ir.model.access.csv',
	'security/odoowarehouse_security.xml',
	 'ERPProject_view1.xml',
	'workflow.xml'],
    'installed': True,
    'auto-install': False,
}